[package]
name = "zeos-verifier"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustzeos = { version = "0.1.0", path = "../rustzeos"}#, features = ["multicore"]}
pasta_curves = { version = "0.4", path = "../pasta_curves" }
wasm-bindgen = { version = "0.2.79" }
byteorder = "1"
#zeos-orchard = { path = "../zeos-orchard"}
#wasm-bindgen-test = "0.2"
#wasm-bindgen-rayon = "1.0"

[dev-dependencies]
zeos-orchard = { path = "../zeos-orchard"}
ff = "0.12"
halo2_proofs = { version = "0.2", path = "../halo2/halo2_proofs" }
rand = "0.8"